/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_uts;
import java.io.File;
import javax.swing.*;
/**
 *
 * @author QC
 */
public class informasi extends javax.swing.JFrame {

    /**
     * Creates new form informasi
     */
    private static informasi instance;
    public informasi() {
        initComponents();
    }
    
    public static informasi getInstance() {
        if (instance == null) {
            instance = new informasi();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 204, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Parfum adalah campuran dari minyak esensial, senyawa aromatik, pelarut, dan fiksatif yang digunakan \nuntuk memberikan aroma wangi pada tubuh, benda, atau ruangan. \nParfum dibuat dengan mencampurkan bahan-bahan aromatik alami (seperti bunga, kayu, rempah-rempah) \ndan/atau bahan sintetis.\n\nBeberapa poin penting tentang parfum:\nKonsentrasi aroma parfum biasanya lebih tinggi dibandingkan jenis wewangian lain seperti eau de toilette atau body mist, \nsehingga wanginya lebih tahan lama.\n\nJenis parfum berdasarkan konsentrasi, antara lain:\n\nParfum (Extrait de Parfum) – paling pekat dan tahan paling lama.\n\nEau de Parfum (EDP) – sedikit lebih ringan dari parfum, tapi tetap tahan lama.\n\nEau de Toilette (EDT) – lebih ringan lagi, cocok untuk penggunaan sehari-hari.\n\nEau de Cologne (EDC) – sangat ringan, biasanya bertahan beberapa jam saja.");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(59, 83, 702, 305);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Abimanyu_Jtab_UTS\\src\\java_uts\\images\\wp11188355.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Method untuk menerima data dari class lain
    public void tampilkanData(String data) {
       jTextArea2.setText(data); 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
